---
title: C28125 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 6
author: mikeblome
ms.author: mblome
manager: jillfra
ms.openlocfilehash: 8a7e44bb7ee5bd51557a9fddc6fee359f39acadf
ms.sourcegitcommit: 08fc78516f1107b83f46e2401888df4868bb1e40
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 05/15/2019
ms.locfileid: "65696789"
---
# <a name="c28125"></a>C28125
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

Advertencia C28125: La funci贸n debe llamarse desde dentro de un bloque try / except bloque  
  
 El controlador llama a una funci贸n que debe llamarse desde dentro de un bloque try / except bloque, como [ProbeForRead](https://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](https://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](https://msdn.microsoft.com/library/windows/hardware/ff554664.aspx).  
  
## <a name="example"></a>Ejemplo  
 El siguiente c贸digo de ejemplo genera esta advertencia:  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 El siguiente c贸digo de ejemplo evita esta advertencia:  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```
