---
title: C6312 | Microsoft Docs
ms.date: 11/15/2016
ms.prod: visual-studio-dev14
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
caps.latest.revision: 15
author: corob-msft
ms.author: corob
manager: jillfra
ms.openlocfilehash: 2f33d2a6e7e87f14859614fa25e1bd846764b944
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77273917"
---
# <a name="c6312"></a>C6312
[!INCLUDE[vs2017banner](../includes/vs2017banner.md)]

ADVERTENCIA C6312: posible bucle infinito: uso de la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-except  
  
 Esta advertencia indica el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como-1) en la expresión de filtro de un controlador de excepciones estructurado. El uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría provocar un bucle infinito. Por ejemplo, si el hardware ha generado una excepción, se reiniciará la instrucción que produjo la excepción. Si la dirección que causó la excepción sigue siendo incorrecta, se producirá otra excepción y se controlará de la misma manera. Esto produce un bucle infinito.  
  
 Una llamada explícita a `RaiseException` no producirá directamente un bucle infinito, pero seguirá la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si se usaba `RaiseException` para evitar desreferenciar un puntero no válido.  
  
 Normalmente, solo se debe devolver `EXCEPTION_CONTINUE_EXECUTION` por una función llamada en la expresión de filtro, que tiene la oportunidad de corregir el puntero que produjo la excepción o la memoria subyacente.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...     
   *ptr = '\0';  
  }   
  __except (EXCEPTION_CONTINUE_EXECUTION)  
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler  
    //  block of the structured exception handler is not executed.   
  {  
    puts("This block is never executed");  
  }  
}  
```  
  
 Para corregir esta advertencia, utilice el código siguiente:  
  
```  
#include <excpt.h>  
#include <stdio.h>  
#include <windows.h>  
  
void f (char *ptr)  
{  
  __try   
  {  
    // exception occurs if the caller passes null ptr  
    // code...  
    *ptr = '\0';  
  }   
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)   
  {  
    puts("Error Occurred");  
  }  
}  
```
