---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: d820ee4244c03368cefc5b9b4af4aa9df11ffdb7
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/08/2019
ms.locfileid: "55907871"
---
# <a name="c28163"></a>C28163
Advertencia C28163: La función nunca debe llamarse desde dentro de un bloque try / except bloque

 Esta advertencia se muestra cuando es una función de un tipo que nunca debe incluirse en un `try/except` bloque se encuentra en un `try/except` bloque. La herramienta de análisis de código encuentra al menos una ruta de acceso en el que la función llamada estaba dentro de un `try/except` bloque.