---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3c810c56c70061fc90cf94bd6730b476cd38d1ff
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/07/2019
ms.locfileid: "72015142"
---
# <a name="c28163"></a>C28163
C28163 de ADVERTENCIA: Nunca se debe llamar a la función desde dentro de un bloque try/except

 Esta advertencia se indica cuando una función es de un tipo que nunca se debe incluir en un bloque `try/except` se encuentra en un bloque `try/except`. La herramienta de análisis de código encontró al menos una ruta de acceso en la que la función llamada estaba dentro de un bloque `try/except`.