---
title: C28163
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28163
helpviewer_keywords:
- C28163
ms.assetid: 24fecbde-1c96-4a45-82f7-9f47cfc0ef11
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 3e9bd974b38647cd330c55df0b8d0063c77bff52
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/16/2019
ms.locfileid: "72434562"
---
# <a name="c28163"></a>C28163
ADVERTENCIA C28163: nunca se debe llamar a la función desde un bloque try/except

 Esta advertencia se indica cuando una función es de un tipo que nunca se debe incluir en un bloque de `try/except` se encuentra en un bloque de `try/except`. La herramienta de análisis de código encontró al menos una ruta de acceso en la que la función llamada estaba dentro de un bloque `try/except`.
