---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 8053149db4b47639bd53961090db6b8bbbef80a9
ms.sourcegitcommit: 485ffaedb1ade71490f11cf05962add1718945cc
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/16/2019
ms.locfileid: "72448411"
---
# <a name="c28105"></a>C28105
ADVERTENCIA C28105: pérdida de recurso debido a una excepción

 El recurso especificado no se libera cuando se produce una excepción. La instrucción especificada por la ruta de acceso puede producir una excepción. Esta advertencia es similar a la advertencia [C28103](../code-quality/c28103.md), salvo que en este caso se trata de una excepción.

## <a name="example"></a>Ejemplo
 El siguiente código de ejemplo genera esta advertencia:

```
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 El siguiente código de ejemplo evita esta advertencia:

```
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
