---
title: C28105
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28105
helpviewer_keywords:
- C28105
ms.assetid: 5afdec78-30eb-470c-980f-93d0cb3e74cc
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 35f138288cc46e1b7a4be34b530f07df7f66caff
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77270190"
---
# <a name="c28105"></a>C28105
ADVERTENCIA C28105: pérdida de recurso debido a una excepción

 El recurso especificado no se libera cuando se produce una excepción. La instrucción especificada por la ruta de acceso puede producir una excepción. Esta advertencia es similar a la advertencia [C28103](../code-quality/c28103.md), salvo que en este caso se trata de una excepción.

## <a name="example"></a>Ejemplo
 El siguiente código de ejemplo genera esta advertencia:

```cpp
res = KeSaveFloatingPointState(buffer);

res = AllocateResource(Resource);
char *p2 = new char[10]; // could throw

delete[] p2;
FreeResource(Resource)
```

 El siguiente código de ejemplo evita esta advertencia:

```cpp
res = AllocateResource(Resource);
char *p2;

try {
    p2 = new char[10];
} catch (std::bad_alloc *e) {
    // just handle the throw
    ;
}
FreeResource(Resource)
```
