---
title: C28125
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C28125
helpviewer_keywords:
- C28125
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: c5811f3174db710985e8fe074fa2785e458d358a
ms.sourcegitcommit: 8589d85cc10710ef87e6363a2effa5ee5610d46a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/23/2019
ms.locfileid: "72806739"
---
# <a name="c28125"></a>C28125
ADVERTENCIA C28125: se debe llamar a la función desde un bloque try/except

 El controlador está llamando a una función a la que se debe llamar desde dentro de un bloque try/except, como [ProbeForRead](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforread), [ProbeForWrite](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-probeforwrite), [MmProbeAndLockPages](/windows-hardware/drivers/ddi/content/wdm/nf-wdm-mmprobeandlockpages).

## <a name="example"></a>Ejemplo
 El siguiente código de ejemplo genera esta advertencia:

```
ProbeForRead(addr, len, 4);
```

 El siguiente código de ejemplo evita esta advertencia:

```

__try
{
    ProbeForRead(addr, len, 4);
}
__except(EXCEPTION_EXECUTE_HANDLER)
{
    Status = GetExceptionCode();
    ... report error status
}
```
