---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 1feeb41725f02985aa35f94815578c5c216ba90f
ms.sourcegitcommit: 535ef05b1e553f0fc66082cd2e0998817eb2a56a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 10/07/2019
ms.locfileid: "72013011"
---
# <a name="c6318"></a>C6318
C6318 de ADVERTENCIA: _ _ Try/@no__t -0 _except: uso de la constante EXCEPTION_CONTINUE_SEARCH u otra constante que se evalúa como cero en la expresión de filtro de excepciones. No se ejecuta el código en el bloque del controlador de excepciones.

 Esta advertencia indica que si se produce una excepción en el bloque protegido de este controlador de excepciones estructurado, la excepción no se controlará porque la constante `EXCECPTION_CONTINUE_SEARCH` se usa en la expresión de filtro de excepción.

 Este código es equivalente al bloque protegido sin el bloque de controlador de excepciones porque no se ejecuta el bloque de controlador.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Vea también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)