---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 0ecf69db24b9c9d970feb818b0342528e9b840eb
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878052"
---
# <a name="c6318"></a>C6318
ADVERTENCIA C6318: _except de\_/__try definidos incorrectamente: uso de la constante EXCEPTION_CONTINUE_SEARCH u otra constante que se evalúa como cero en la expresión de filtro de excepciones. No se ejecutará el código en el bloque del controlador de excepciones

 Esta advertencia indica que si se produce una excepción en el bloque protegido de este controlador de excepciones estructurado, la excepción no se controlará porque la constante `EXCECPTION_CONTINUE_SEARCH` se usa en la expresión de filtro de excepción.

 Este código es equivalente al bloque protegido sin el bloque de controlador de excepciones porque no se ejecuta el bloque de controlador.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Vea también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)
