---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 683619442865a231742fdecba9e94a893d103144
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/15/2020
ms.locfileid: "77267029"
---
# <a name="c6318"></a>C6318
ADVERTENCIA C6318: _except de\_/__try definidos incorrectamente: uso de la constante EXCEPTION_CONTINUE_SEARCH u otra constante que se evalúa como cero en la expresión de filtro de excepciones. No se ejecuta el código en el bloque del controlador de excepciones.

 Esta advertencia indica que si se produce una excepción en el bloque protegido de este controlador de excepciones estructurado, la excepción no se controlará porque la constante `EXCECPTION_CONTINUE_SEARCH` se usa en la expresión de filtro de excepción.

 Este código es equivalente al bloque protegido sin el bloque de controlador de excepciones porque no se ejecuta el bloque de controlador.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```cpp
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```cpp
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Consulte también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)
