---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: f472860cd338dee15b4005db16ba09de1e314071
ms.sourcegitcommit: 21d667104199c2493accec20c2388cf674b195c3
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 02/08/2019
ms.locfileid: "55920891"
---
# <a name="c6318"></a>C6318
Advertencia C6318: Definido correctamente __try /\__except: uso de la constante EXCEPTION_CONTINUE_SEARCH u otra que evalúe en cero en la expresión de filtro de excepciones. No se ejecuta el código en el bloque de controlador de excepciones

 Esta advertencia indica que si se produce una excepción en el bloque protegido de este controlador de excepciones estructurado, la excepción no se controlará porque la constante `EXCECPTION_CONTINUE_SEARCH` se utiliza en la expresión de filtro de excepción.

 Este código es equivalente al bloque protegido sin el bloque de controlador de excepciones porque no se ejecuta el bloque del controlador.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>Vea también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)