---
title: C6322
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6322
helpviewer_keywords:
- C6322
ms.assetid: fb23d2b1-b2a0-465c-8bf5-ec039c6c7757
author: mikeblome
ms.author: mblome
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: 91103238c933fbd017617b44769b86c98c0bd324
ms.sourcegitcommit: 174c992ecdc868ecbf7d3cee654bbc2855aeb67d
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 12/06/2019
ms.locfileid: "74878013"
---
# <a name="c6322"></a>C6322
Advertencia C6322: Bloque empty _except

 Este mensaje indica que no hay ningún código en el bloque _except. Como resultado, es posible que las excepciones no estén controladas.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void fd(char *pch)
{
   __try
   {
     // exception rasied if pch is null
     *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION)
   {
   }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```cpp
#include <stdio.h>
#include <excpt.h>
#include <windows.h>

void f(char *pch)
{
   __try
   {
     // exception rasied if pch is null
    *pch= 0 ;
   }
   __except(GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
     // code to handle exception
     puts("Exception Occurred");
   }
}
```

## <a name="see-also"></a>Vea también
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)
